import '../l10n/app_localizations.dart';

/// Maps Japanese prefecture, city, ward, and district names to their localization keys.
/// Returns the localized name based on the current app locale (Japanese, English, Chinese).
/// Falls back to the original location name if no localization is available.
String getLocalizedLocationName(String locationName, AppLocalizations localizations) {
  final localizationMap = {
    // ============================================================================
    // HOKKAIDO REGION
    // ============================================================================

    // --- Hokkaido Prefecture ---
    'Hokkaido': localizations.cityHokkaido,
    'Sapporo': localizations.citySapporo,
    'Hakodate': localizations.cityHakodate,
    'Asahikawa': localizations.cityAsahikawa,
    'Otaru': localizations.cityOtaru,
    'Kushiro': localizations.cityKushiro,
    'Obihiro': localizations.cityObihiro,
    'Kitami': localizations.cityKitami,
    'Tomakomai': localizations.cityTomakomai,
    'Muroran': localizations.cityMuroran,
    'Chitose': localizations.cityChitose,
    'Ebetsu': localizations.cityEbetsu,
    'Abashiri': localizations.cityAbashiri,
    'Rumoi': localizations.cityRumoi,
    'Wakkanai': localizations.cityWakkanai,
    'Bibai': localizations.cityBibai,
    'Nemuro': localizations.cityNemuro,
    'Monbetsu': localizations.cityMonbetsu,
    'Ishikari': localizations.cityIshikari,
    'Nayoro': localizations.cityNayoro,
    'Mikasa': localizations.cityMikasa,
    'Takikawa': localizations.cityTakikawa,
    'Sunagawa': localizations.citySunagawa,
    'Utashinai': localizations.cityUtashinai,
    'Fukagawa': localizations.cityFukagawa,
    'Furano': localizations.cityFurano,
    'Noboribetsu': localizations.cityNoboribetsu,
    'Eniwa': localizations.cityEniwa,
    'Date': localizations.cityDate,
    'Kitahiroshima': localizations.cityKitahiroshima,
    'Hokuto': localizations.cityHokuto,
    'Yubari': localizations.cityYubari,
    'Iwamizawa': localizations.cityIwamizawa,
    'Shibetsu': localizations.cityShibetsu,
    'Niseko': localizations.cityNiseko,

    // ============================================================================
    // TOHOKU REGION
    // ============================================================================

    // --- Aomori Prefecture ---
    'Aomori': localizations.cityAomori,
    'Aomori City': localizations.cityAomoriCity,
    'Hirosaki': localizations.cityHirosaki,
    'Hachinohe': localizations.cityHachinohe,
    'Misawa': localizations.cityMisawa,
    'Mutsu': localizations.cityMutsu,
    'Towada': localizations.cityTowada,
    'Goshogawara': localizations.cityGoshogawara,
    'Kuroishi': localizations.cityKuroishi,
    'Tsugaru': localizations.cityTsugaru,
    'Hirakawa': localizations.cityHirakawa,

    // --- Iwate Prefecture ---
    'Iwate': localizations.cityIwate,
    'Morioka': localizations.cityMorioka,
    'Miyako': localizations.cityMiyako,
    'Ofunato': localizations.cityOfunato,
    'Hanamaki': localizations.cityHanamaki,
    'Kitakami': localizations.cityKitakami,
    'Kamaishi': localizations.cityKamaishi,
    'Ichinoseki': localizations.cityIchinoseki,
    'Rikuzentakata': localizations.cityRikuzentakata,
    'Tono': localizations.cityTono,
    'Hachimantai': localizations.cityHachimantai,
    'Oshu': localizations.cityOshu,
    'Takizawa': localizations.cityTakizawa,
    'Shiwa': localizations.cityShiwa,

    // --- Miyagi Prefecture ---
    'Miyagi': localizations.cityMiyagi,
    'Sendai': localizations.citySendai,
    'Ishinomaki': localizations.cityIshinomaki,
    'Shiogama': localizations.cityShiogama,
    'Kesennuma': localizations.cityKesennuma,
    'Shiroishi': localizations.cityShiroishi,
    'Natori': localizations.cityNatori,
    'Kakuda': localizations.cityKakuda,
    'Tagajo': localizations.cityTagajo,
    'Iwanuma': localizations.cityIwanuma,
    'Tome': localizations.cityTome,
    'Kurihara': localizations.cityKurihara,
    'Higashimatsushima': localizations.cityHigashimatsushima,
    'Osaki': localizations.cityOsaki,
    'Tomiya': localizations.cityTomiya,

    // --- Akita Prefecture ---
    'Akita': localizations.cityAkita,
    'Akita City': localizations.cityAkitaCity,
    'Noshiro': localizations.cityNoshiro,
    'Yokote': localizations.cityYokote,
    'Odate': localizations.cityOdate,
    'Kazuno': localizations.cityKazuno,
    'Yuzawa': localizations.cityYuzawa,
    'Daisen': localizations.cityDaisen,
    'Katagami': localizations.cityKatagami,
    'Semboku': localizations.citySemboku,
    'Nikaho': localizations.cityNikaho,

    // --- Yamagata Prefecture ---
    'Yamagata': localizations.cityYamagata,
    'Yamagata City': localizations.cityYamagataCity,
    'Yonezawa': localizations.cityYonezawa,
    'Tsuruoka': localizations.cityTsuruoka,
    'Sakata': localizations.citySakata,
    'Shinjo': localizations.cityShinjo,
    'Sagae': localizations.citySagae,
    'Kaminoyama': localizations.cityKaminoyama,
    'Murayama': localizations.cityMurayama,
    'Nagai': localizations.cityNagai,
    'Tendo': localizations.cityTendo,
    'Higashine': localizations.cityHigashine,
    'Obanazawa': localizations.cityObanazawa,
    'Nanyo': localizations.cityNanyo,

    // --- Fukushima Prefecture ---
    'Fukushima': localizations.cityFukushima,
    'Fukushima City': localizations.cityFukushimaCity,
    'Koriyama': localizations.cityKoriyama,
    'Iwaki': localizations.cityIwaki,
    'Aizuwakamatsu': localizations.cityAizuwakamatsu,
    'Sukagawa': localizations.citySukagawa,
    'Kitakata': localizations.cityKitakata,
    'Soma': localizations.citySoma,
    'Nihonmatsu': localizations.cityNihonmatsu,
    'Tamura': localizations.cityTamura,
    'Minamisoma': localizations.cityMinamisoma,
    'Motomiya': localizations.cityMotomiya,

    // ============================================================================
    // KANTO REGION
    // ============================================================================

    // --- Ibaraki Prefecture ---
    'Ibaraki': localizations.cityIbaraki,
    'Mito': localizations.cityMito,
    'Hitachi': localizations.cityHitachi,
    'Hitachiota': localizations.cityHitachiota,
    'Tsuchiura': localizations.cityTsuchiura,
    'Tsukuba': localizations.cityTsukuba,
    'Koga': localizations.cityKoga,
    'Ishioka': localizations.cityIshioka,
    'Kasama': localizations.cityKasama,
    'Kitaibaraki': localizations.cityKitaibaraki,
    'Takahagi': localizations.cityTakahagi,
    'Toride': localizations.cityToride,
    'Ushiku': localizations.cityUshiku,

    // --- Tochigi Prefecture ---
    'Tochigi': localizations.cityTochigi,
    'Utsunomiya': localizations.cityUtsunomiya,
    'Ashikaga': localizations.cityAshikaga,
    'Sano': localizations.citySano,
    'Kanuma': localizations.cityKanuma,
    'Nikko': localizations.cityNikko,
    'Oyama': localizations.cityOyama,
    'Moka': localizations.cityMoka,
    'Ohtawara': localizations.cityOhtawara,
    'Yaita': localizations.cityYaita,
    'Nasushiobara': localizations.cityNasushiobara,
    'Sakura': localizations.citySakura,

    // --- Gunma Prefecture ---
    'Gunma': localizations.cityGunma,
    'Maebashi': localizations.cityMaebashi,
    'Takasaki': localizations.cityTakasaki,
    'Kiryu': localizations.cityKiryu,
    'Isesaki': localizations.cityIsesaki,
    'Ota': localizations.cityOta,
    'Numata': localizations.cityNumata,
    'Tatebayashi': localizations.cityTatebayashi,
    'Fujioka': localizations.cityFujioka,
    'Annaka': localizations.cityAnnaka,
    'Tomioka': localizations.cityTomioka,
    'Shibukawa': localizations.cityShibukawa,

    // --- Saitama Prefecture ---
    'Saitama': localizations.citySaitama,
    'Saitama City': localizations.citySaitama,
    'Kawagoe': localizations.cityKawagoe,
    'Kawaguchi': localizations.cityKawaguchi,
    'Tokorozawa': localizations.cityTokorozawa,
    'Kumagaya': localizations.cityKumagaya,
    'Koshigaya': localizations.cityKoshigaya,
    'Kasukabe': localizations.cityKasukabe,
    'Fukaya': localizations.cityFukaya,
    'Ageo': localizations.cityAgeo,
    'Soka': localizations.citySoka,
    'Hanno': localizations.cityHanno,
    'Niiza': localizations.cityNiiza,
    'Sayama': localizations.citySayama,

    // --- Chiba Prefecture ---
    'Chiba': localizations.cityChiba,
    'Chiba City': localizations.cityChibaCity,
    'Funabashi': localizations.cityFunabashi,
    'Matsudo': localizations.cityMatsudo,
    'Ichikawa': localizations.cityIchikawa,
    'Kashiwa': localizations.cityKashiwa,
    'Ichihara': localizations.cityIchihara,
    'Narita': localizations.cityNarita,
    'Urayasu': localizations.cityUrayasu,
    'Kisarazu': localizations.cityKisarazu,
    'Narashino': localizations.cityNarashino,
    'Yachiyo': localizations.cityYachiyo,
    'Abiko': localizations.cityAbiko,
    'Noda': localizations.cityNoda,

    // --- Tokyo Prefecture ---
    'Tokyo': localizations.cityTokyo,
    'Shibuya': localizations.cityShibuya,
    'Harajuku': localizations.cityHarajuku,
    'Ebisu': localizations.cityEbisu,
    'Shinjuku': localizations.cityShinjuku,
    'Kabukicho': localizations.cityKabukicho,
    'Yotsuya': localizations.cityYotsuya,
    'Chiyoda': localizations.cityChiyoda,
    'Marunouchi': localizations.cityMarunouchi,
    'Akihabara': localizations.cityAkihabara,
    'Kanda': localizations.cityKanda,
    'Minato': localizations.cityMinato,
    'Roppongi': localizations.cityRoppongi,
    'Azabu': localizations.cityAzabu,
    'Odaiba': localizations.cityOdaiba,
    'Setagaya': localizations.citySetagaya,
    'Shimokitazawa': localizations.cityShimokitazawa,
    'Sangenjaya': localizations.citySangenjaya,
    'Kita': localizations.cityKita,
    'Adachi': localizations.cityAdachi,
    'Arakawa': localizations.cityArakawa,
    'Bunkyo': localizations.cityBunkyo,
    'Edogawa': localizations.cityEdogawa,
    'Itabashi': localizations.cityItabashi,
    'Katsushika': localizations.cityKatsushika,
    'Koto': localizations.cityKoto,
    'Meguro': localizations.cityMeguro,
    'Nakano': localizations.cityNakano,
    'Nerima': localizations.cityNerima,
    'Ota Ward': localizations.cityOtaWard,
    'Shinagawa': localizations.cityShinagawa,
    'Suginami': localizations.citySuginami,
    'Sumida': localizations.citySumida,
    'Taito': localizations.cityTaito,
    'Toshima': localizations.cityToshima,

    // --- Kanagawa Prefecture ---
    'Kanagawa': localizations.cityKanagawa,
    'Yokohama': localizations.cityYokohama,
    'Chinatown': localizations.cityChinatown,
    'Minato Mirai': localizations.cityMinatoMirai,
    'Naka': localizations.cityNaka,
    'Kawasaki': localizations.cityKawasaki,
    'Sagamihara': localizations.citySagamihara,
    'Fujisawa': localizations.cityFujisawa,
    'Yokosuka': localizations.cityYokosuka,
    'Hiratsuka': localizations.cityHiratsuka,
    'Kamakura': localizations.cityKamakura,
    'Odawara': localizations.cityOdawara,
    'Chigasaki': localizations.cityChigasaki,
    'Atsugi': localizations.cityAtsugi,
    'Yamato': localizations.cityYamato,
    'Zushi': localizations.cityZushi,
    'Ebina': localizations.cityEbina,
    'Miura': localizations.cityMiura,
    'Hadano': localizations.cityHadano,
    'Isehara': localizations.cityIsehara,
    'Minamiashigara': localizations.cityMinamiashigara,
    'Ayase': localizations.cityAyase,
    'Tsurumi': localizations.cityTsurumi,
    'Kanagawa Ward': localizations.cityKanagawaWard,
    'Kohoku': localizations.cityKohoku,
    'Totsuka': localizations.cityTotsuka,
    'Hodogaya': localizations.cityHodogaya,
    'Isogo': localizations.cityIsogo,
    'Kanazawa Ward': localizations.cityKanazawaWard,
    'Konan Ward': localizations.cityKonanWard,
    'Asahi': localizations.cityAsahi,
    'Midori': localizations.cityMidori,
    'Seya': localizations.citySeya,
    'Sakae': localizations.citySakae,
    'Izumi Ward': localizations.cityIzumiWard,
    'Aoba': localizations.cityAoba,
    'Tsuzuki': localizations.cityTsuzuki,
    'Nishi': localizations.cityNishi,
    'Minami': localizations.cityMinami,
    'Naka Ward': localizations.cityNakaWard,

    // ============================================================================
    // CHUBU REGION
    // ============================================================================

    // --- Niigata Prefecture ---
    'Niigata': localizations.cityNiigata,
    'Niigata City': localizations.cityNiigataCity,
    'Nagaoka': localizations.cityNagaoka,
    'Joetsu': localizations.cityJoetsu,
    'Sanjo': localizations.citySanjo,
    'Kashiwazaki': localizations.cityKashiwazaki,
    'Shibata': localizations.cityShibata,
    'Ojiya': localizations.cityOjiya,
    'Kamo': localizations.cityKamo,
    'Tokamachi': localizations.cityTokamachi,
    'Tsubame': localizations.cityTsubame,
    'Itoigawa': localizations.cityItoigawa,
    'Myoko': localizations.cityMyoko,

    // --- Toyama Prefecture ---
    'Toyama': localizations.cityToyama,
    'Toyama City': localizations.cityToyamaCity,
    'Takaoka': localizations.cityTakaoka,
    'Uozu': localizations.cityUozu,
    'Himi': localizations.cityHimi,
    'Namerikawa': localizations.cityNamerikawa,
    'Kurobe': localizations.cityKurobe,
    'Tonami': localizations.cityTonami,
    'Oyabe': localizations.cityOyabe,
    'Nanto': localizations.cityNanto,
    'Imizu': localizations.cityImizu,

    // --- Ishikawa Prefecture ---
    'Ishikawa': localizations.cityIshikawa,
    'Kanazawa': localizations.cityKanazawa,
    'Nanao': localizations.cityNanao,
    'Komatsu': localizations.cityKomatsu,
    'Wajima': localizations.cityWajima,
    'Suzu': localizations.citySuzu,
    'Kaga': localizations.cityKaga,
    'Hakui': localizations.cityHakui,
    'Kahoku': localizations.cityKahoku,
    'Hakusan': localizations.cityHakusan,
    'Nomi': localizations.cityNomi,
    'Nonoichi': localizations.cityNonoichi,

    // --- Fukui Prefecture ---
    'Fukui': localizations.cityFukui,
    'Fukui City': localizations.cityFukuiCity,
    'Tsuruga': localizations.cityTsuruga,
    'Obama': localizations.cityObama,
    'Ono': localizations.cityOno,
    'Katsuyama': localizations.cityKatsuyama,
    'Sabae': localizations.citySabae,
    'Awara': localizations.cityAwara,
    'Echizen': localizations.cityEchizen,

    // --- Yamanashi Prefecture ---
    'Yamanashi': localizations.cityYamanashi,
    'Kofu': localizations.cityKofu,
    'Fujiyoshida': localizations.cityFujiyoshida,
    'Tsuru': localizations.cityTsuru,
    'Otsuki': localizations.cityOtsuki,
    'Nirasaki': localizations.cityNirasaki,
    'Minami-Alps': localizations.cityMinamiAlps,
    'Kai': localizations.cityKai,
    'Fuefuki': localizations.cityFuefuki,
    'Uenohara': localizations.cityUenohara,
    'Koshu': localizations.cityKoshu,
    'Chuo': localizations.cityChuo,

    // --- Nagano Prefecture ---
    'Nagano': localizations.cityNagano,
    'Nagano City': localizations.cityNaganoCity,
    'Matsumoto': localizations.cityMatsumoto,
    'Ueda': localizations.cityUeda,
    'Okaya': localizations.cityOkaya,
    'Suwa': localizations.citySuwa,
    'Suzaka': localizations.citySuzaka,
    'Chino': localizations.cityChino,
    'Shiojiri': localizations.cityShiojiri,
    'Saku': localizations.citySaku,
    'Chikuma': localizations.cityChikuma,
    'Tomi': localizations.cityTomi,
    'Azumino': localizations.cityAzumino,
    'Komagane': localizations.cityKomagane,

    // --- Gifu Prefecture ---
    'Gifu': localizations.cityGifu,
    'Gifu City': localizations.cityGifuCity,
    'Ogaki': localizations.cityOgaki,
    'Takayama': localizations.cityTakayama,
    'Tajimi': localizations.cityTajimi,
    'Seki': localizations.citySeki,
    'Nakatsugawa': localizations.cityNakatsugawa,
    'Mino': localizations.cityMino,
    'Mizunami': localizations.cityMizunami,
    'Hashima': localizations.cityHashima,
    'Ena': localizations.cityEna,
    'Minokamo': localizations.cityMinokamo,
    'Toki': localizations.cityToki,
    'Kakamigahara': localizations.cityKakamigahara,
    'Kani': localizations.cityKani,
    'Mizuho': localizations.cityMizuho,
    'Hida': localizations.cityHida,
    'Motosu': localizations.cityMotosu,
    'Gero': localizations.cityGero,

    // --- Shizuoka Prefecture ---
    'Shizuoka': localizations.cityShizuoka,
    'Shizuoka City': localizations.cityShizuokaCity,
    'Hamamatsu': localizations.cityHamamatsu,
    'Numazu': localizations.cityNumazu,
    'Atami': localizations.cityAtami,
    'Mishima': localizations.cityMishima,
    'Fujinomiya': localizations.cityFujinomiya,
    'Ito': localizations.cityIto,
    'Shimada': localizations.cityShimada,
    'Iwata': localizations.cityIwata,
    'Yaizu': localizations.cityYaizu,
    'Kakegawa': localizations.cityKakegawa,
    'Fujieda': localizations.cityFujieda,
    'Gotemba': localizations.cityGotemba,
    'Fukuroi': localizations.cityFukuroi,
    'Shimoda': localizations.cityShimoda,
    'Susono': localizations.citySusono,
    'Kosai': localizations.cityKosai,
    'Izu': localizations.cityIzu,
    'Omaezaki': localizations.cityOmaezaki,
    'Kikugawa': localizations.cityKikugawa,
    'Izunokuni': localizations.cityIzunokuni,
    'Makinohara': localizations.cityMakinohara,

    // --- Aichi Prefecture ---
    'Aichi': localizations.cityAichi,
    'Nagoya': localizations.cityNagoya,
    'Toyohashi': localizations.cityToyohashi,
    'Ichinomiya': localizations.cityIchinomiya,
    'Seto': localizations.citySeto,
    'Kasugai': localizations.cityKasugai,
    'Toyokawa': localizations.cityToyokawa,
    'Tsushima': localizations.cityTsushima,
    'Hekinan': localizations.cityHekinan,
    'Kariya': localizations.cityKariya,
    'Toyota': localizations.cityToyota,
    'Anjo': localizations.cityAnjo,
    'Nishio': localizations.cityNishio,
    'Gamagori': localizations.cityGamagori,
    'Inuyama': localizations.cityInuyama,
    'Tokoname': localizations.cityTokoname,
    'Konan': localizations.cityKonan,
    'Komaki': localizations.cityKomaki,
    'Inazawa': localizations.cityInazawa,
    'Tokai': localizations.cityTokai,
    'Obu': localizations.cityObu,
    'Chita': localizations.cityChita,
    'Chiryu': localizations.cityChiryu,
    'Owariasahi': localizations.cityOwariasahi,
    'Takahama': localizations.cityTakahama,
    'Iwakura': localizations.cityIwakura,
    'Kiyosu': localizations.cityKiyosu,
    'Kitanagoya': localizations.cityKitanagoya,
    'Yatomi': localizations.cityYatomi,
    'Miyoshi': localizations.cityMiyoshi,
    'Ama': localizations.cityAma,
    'Nagakute': localizations.cityNagakute,
    'Aisai': localizations.cityAisai,

    // ============================================================================
    // KANSAI REGION
    // ============================================================================

    // --- Mie Prefecture ---
    'Mie': localizations.cityMie,
    'Tsu': localizations.cityTsu,
    'Yokkaichi': localizations.cityYokkaichi,
    'Ise': localizations.cityIse,
    'Matsusaka': localizations.cityMatsusaka,
    'Kuwana': localizations.cityKuwana,
    'Suzuka': localizations.citySuzuka,
    'Nabari': localizations.cityNabari,
    'Owase': localizations.cityOwase,
    'Kameyama': localizations.cityKameyama,
    'Toba': localizations.cityToba,
    'Kumano': localizations.cityKumano,
    'Inabe': localizations.cityInabe,
    'Shima': localizations.cityShima,
    'Iga': localizations.cityIga,

    // --- Shiga Prefecture ---
    'Shiga': localizations.cityShiga,
    'Otsu': localizations.cityOtsu,
    'Hikone': localizations.cityHikone,
    'Nagahama': localizations.cityNagahama,
    'Omihachiman': localizations.cityOmihachiman,
    'Kusatsu': localizations.cityKusatsu,
    'Moriyama': localizations.cityMoriyama,
    'Ritto': localizations.cityRitto,
    'Koka': localizations.cityKoka,
    'Yasu': localizations.cityYasu,
    'Takashima': localizations.cityTakashima,
    'Higashiomi': localizations.cityHigashiomi,
    'Maibara': localizations.cityMaibara,

    // --- Kyoto Prefecture ---
    'Kyoto': localizations.cityKyoto,
    'Kyoto Station Area': localizations.cityKyotoStationArea,
    'Shimogyo': localizations.cityShimogyo,
    'Higashiyama': localizations.cityHigashiyama,
    'Gion': localizations.cityGion,
    'Kiyomizu': localizations.cityKiyomizu,
    'Sakyo': localizations.citySakyo,
    'Ginkakuji Area': localizations.cityGinkakujiArea,
    'Kamigyo': localizations.cityKamigyo,
    'Nakagyo': localizations.cityNakagyo,
    'Fushimi': localizations.cityFushimi,
    'Ukyo': localizations.cityUkyo,
    'Yamashina': localizations.cityYamashina,
    'Nishikyo': localizations.cityNishikyo,
    'Arashiyama': localizations.cityArashiyama,
    'Kinkakuji Area': localizations.cityKinkakujiArea,
    'Uji': localizations.cityUji,
    'Kameoka': localizations.cityKameoka,
    'Joyo': localizations.cityJoyo,
    'Muko': localizations.cityMuko,
    'Nagaokakyo': localizations.cityNagaokakyo,
    'Yawata': localizations.cityYawata,
    'Kyotanabe': localizations.cityKyotanabe,
    'Kyotango': localizations.cityKyotango,
    'Nantan': localizations.cityNantan,
    'Kizugawa': localizations.cityKizugawa,

    // --- Osaka Prefecture ---
    'Osaka': localizations.cityOsaka,
    // Wards (note: Kita, Chuo, Nishi, Minato, Asahi, Tsurumi are defined elsewhere)
    'Tennoji': localizations.cityTennoji,
    'Naniwa': localizations.cityNaniwa,
    'Yodogawa': localizations.cityYodogawa,
    'Higashiyodogawa': localizations.cityHigashiyodogawa,
    'Higashinari': localizations.cityHigashinari,
    'Ikuno': localizations.cityIkuno,
    'Joto': localizations.cityJoto,
    'Abeno': localizations.cityAbeno,
    'Sumiyoshi': localizations.citySumiyoshi,
    'Higashisumiyoshi': localizations.cityHigashisumiyoshi,
    'Nishinari': localizations.cityNishinari,
    'Taisho': localizations.cityTaisho,
    'Suminoe': localizations.citySuminoe,
    'Konohana': localizations.cityKonohana,
    'Hirano': localizations.cityHirano,
    'Miyakojima': localizations.cityMiyakojima,
    // Districts and Areas
    'Umeda': localizations.cityUmeda,
    'Nakanoshima': localizations.cityNakanoshima,
    'Namba': localizations.cityNamba,
    'Shinsaibashi': localizations.cityShinsaibashi,
    'Dotonbori': localizations.cityDotonbori,
    // Cities (note: Ibaraki is defined in Kanto region)
    'Sakai': localizations.citySakai,
    'Hirakata': localizations.cityHirakata,
    'Toyonaka': localizations.cityToyonaka,
    'Takatsuki': localizations.cityTakatsuki,
    'Suita': localizations.citySuita,
    'Moriguchi': localizations.cityMoriguchi,
    'Kadoma': localizations.cityKadoma,
    'Neyagawa': localizations.cityNeyagawa,
    'Kawachinagano': localizations.cityKawachinagano,
    'Matsubara': localizations.cityMatsubara,
    'Daito': localizations.cityDaito,
    'Izumi': localizations.cityIzumi,
    'Izumiotsu': localizations.cityIzumiotsu,
    'Izumisano': localizations.cityIzumisano,
    'Tondabayashi': localizations.cityTondabayashi,
    'Kashiwara': localizations.cityKashiwara,
    'Habikino': localizations.cityHabikino,
    'Katano': localizations.cityKatano,
    'Osaka Sayama': localizations.cityOsakasayama,
    'Hannan': localizations.cityHannan,
    'Shijonawate': localizations.cityShijonawate,

    // --- Hyogo Prefecture ---
    'Hyogo': localizations.cityHyogo,
    'Kobe': localizations.cityKobe,
    'Himeji': localizations.cityHimeji,
    'Amagasaki': localizations.cityAmagasaki,
    'Akashi': localizations.cityAkashi,
    'Nishinomiya': localizations.cityNishinomiya,
    'Takarazuka': localizations.cityTakarazuka,
    'Itami': localizations.cityItami,
    'Kakogawa': localizations.cityKakogawa,
    'Takasago': localizations.cityTakasago,
    'Toyooka': localizations.cityToyooka,
    'Ako': localizations.cityAko,
    'Nishiwaki': localizations.cityNishiwaki,
    'Tatsuno': localizations.cityTatsuno,
    'Sanda': localizations.citySanda,
    'Yabu': localizations.cityYabu,
    'Kasai': localizations.cityKasai,
    'Sasayama': localizations.citySasayama,
    'Asago': localizations.cityAsago,
    'Aioi': localizations.cityAioi,
    'Miki': localizations.cityMiki,
    'Kawanishi': localizations.cityKawanishi,
    'Tamba': localizations.cityTamba,
    'Minamiawaji': localizations.cityMinamiawaji,
    'Awaji': localizations.cityAwaji,
    'Sumoto': localizations.citySumoto,
    'Shiso': localizations.cityShiso,

    // --- Nara Prefecture ---
    'Nara': localizations.cityNara,
    'Nara City': localizations.cityNaraCity,
    'Yamatokoriyama': localizations.cityYamatokoriyama,
    'Yamatotakada': localizations.cityYamatoTakada,
    'Tenri': localizations.cityTenri,
    'Kashihara': localizations.cityKashihara,
    'Sakurai': localizations.citySakurai,
    'Gojo': localizations.cityGojo,
    'Gose': localizations.cityGose,
    'Ikoma': localizations.cityIkoma,
    'Kashiba': localizations.cityKashiba,
    'Katsuragi': localizations.cityKatsuragi,
    'Uda': localizations.cityUda,

    // --- Wakayama Prefecture ---
    'Wakayama': localizations.cityWakayama,
    'Wakayama City': localizations.cityWakayamaCity,
    'Kainan': localizations.cityKainan,
    'Hashimoto': localizations.cityHashimoto,
    'Arida': localizations.cityArida,
    'Gobo': localizations.cityGobo,
    'Tanabe': localizations.cityTanabe,
    'Shingu': localizations.cityShingu,
    'Kinokawa': localizations.cityKinokawa,
    'Iwade': localizations.cityIwade,

    // ============================================================================
    // CHUGOKU REGION
    // ============================================================================

    // --- Tottori Prefecture ---
    // (No cities listed in prefecture_data.dart for Tottori)

    // --- Shimane Prefecture ---
    // (No cities listed in prefecture_data.dart for Shimane)

    // --- Okayama Prefecture ---
    'Okayama': localizations.cityOkayama,
    'Okayama City': localizations.cityOkayamaCity,
    'Kurashiki': localizations.cityKurashiki,
    'Tsuyama': localizations.cityTsuyama,
    'Tamano': localizations.cityTamano,
    'Kasaoka': localizations.cityKasaoka,
    'Ibara': localizations.cityIbara,
    'Soja': localizations.citySoja,
    'Takahashi': localizations.cityTakahashi,
    'Niimi': localizations.cityNiimi,
    'Bizen': localizations.cityBizen,
    'Setouchi': localizations.citySetouchi,
    'Akaiwa': localizations.cityAkaiwa,
    'Maniwa': localizations.cityManiwa,
    'Mimasaka': localizations.cityMimasaka,
    'Asakuchi': localizations.cityAsakuchi,

    // --- Hiroshima Prefecture ---
    'Hiroshima': localizations.cityHiroshima,
    'Hiroshima City': localizations.cityHiroshimaCity,
    'Kure': localizations.cityKure,
    'Takehara': localizations.cityTakehara,
    'Mihara': localizations.cityMihara,
    'Onomichi': localizations.cityOnomichi,
    'Fukuyama': localizations.cityFukuyama,
    'Fuchu': localizations.cityFuchu,
    'Shobara': localizations.cityShobara,
    'Otake': localizations.cityOtake,
    'Higashihiroshima': localizations.cityHigashihiroshima,
    'Hatsukaichi': localizations.cityHatsukaichi,
    'Akitakata': localizations.cityAkitakata,
    'Etajima': localizations.cityEtajima,

    // --- Yamaguchi Prefecture ---
    'Yamaguchi': localizations.cityYamaguchi,
    'Yamaguchi City': localizations.cityYamaguchiCity,
    'Shimonoseki': localizations.cityShimonoseki,
    'Ube': localizations.cityUbe,
    'Hagi': localizations.cityHagi,
    'Hofu': localizations.cityHofu,
    'Kudamatsu': localizations.cityKudamatsu,
    'Iwakuni': localizations.cityIwakuni,
    'Hikari': localizations.cityHikari,
    'Nagato': localizations.cityNagato,
    'Yanai': localizations.cityYanai,
    'Mine': localizations.cityMine,
    'Shunan': localizations.cityShunan,
    'Sanyo-Onoda': localizations.citySanyoOnoda,

    // ============================================================================
    // SHIKOKU REGION
    // ============================================================================

    // --- Tokushima Prefecture ---
    'Tokushima': localizations.cityTokushima,
    'Tokushima City': localizations.cityTokushimaCity,
    'Naruto': localizations.cityNaruto,
    'Komatsushima': localizations.cityKomatsushima,
    'Anan': localizations.cityAnan,
    'Yoshinogawa': localizations.cityYoshinogawa,
    'Awa': localizations.cityAwa,
    'Mima': localizations.cityMima,

    // --- Kagawa Prefecture ---
    'Kagawa': localizations.cityKagawa,
    'Takamatsu': localizations.cityTakamatsu,
    'Marugame': localizations.cityMarugame,
    'Sakaide': localizations.citySakaide,
    'Zentsuji': localizations.cityZentsuji,
    'Kan\'onji': localizations.cityKannonji,
    'Sanuki': localizations.citySanuki,
    'Higashikagawa': localizations.cityHigashikagawa,
    'Mitoyo': localizations.cityMitoyo,

    // --- Ehime Prefecture ---
    'Ehime': localizations.cityEhime,
    'Matsuyama': localizations.cityMatsuyama,
    'Imabari': localizations.cityImabari,
    'Uwajima': localizations.cityUwajima,
    'Yawatahama': localizations.cityYawatahama,
    'Niihama': localizations.cityNiihama,
    'Saijo': localizations.citySaijo,
    'Ozu': localizations.cityOzu,
    'Iyo': localizations.cityIyo,
    'Shikokuchuo': localizations.cityShikokuchuo,
    'Seiyo': localizations.citySeiyo,
    'Toon': localizations.cityToon,

    // --- Kochi Prefecture ---
    'Kochi': localizations.cityKochi,
    'Kochi City': localizations.cityKochiCity,
    'Muroto': localizations.cityMuroto,
    'Aki': localizations.cityAki,
    'Nankoku': localizations.cityNankoku,
    'Tosa': localizations.cityTosa,
    'Susaki': localizations.citySusaki,
    'Sukumo': localizations.citySukumo,
    'Tosashimizu': localizations.cityTosashimizu,
    'Shimanto': localizations.cityShimanto,
    'Kami': localizations.cityKami,

    // ============================================================================
    // KYUSHU & OKINAWA REGION
    // ============================================================================

    // --- Fukuoka Prefecture ---
    'Fukuoka': localizations.cityFukuoka,
    'Hakata': localizations.cityHakata,
    'Higashi': localizations.cityHigashi,
    'Sawara': localizations.citySawara,
    'Jonan': localizations.cityJonan,
    'Hakata Station Area': localizations.cityHakataStationArea,
    'Canal City': localizations.cityCanalCity,
    'Tenjin': localizations.cityTenjin,
    'Tenjin Central': localizations.cityTenjinCentral,
    'Kitakyushu': localizations.cityKitakyushu,
    'Kurume': localizations.cityKurume,
    'Omuta': localizations.cityOmuta,
    'Nogata': localizations.cityNogata,
    'Tagawa': localizations.cityTagawa,
    'Yanagawa': localizations.cityYanagawa,
    'Yame': localizations.cityYame,
    'Chikugo': localizations.cityChikugo,
    'Okawa': localizations.cityOkawa,
    'Yukuhashi': localizations.cityYukuhashi,
    'Buzen': localizations.cityBuzen,
    'Nakama': localizations.cityNakama,
    'Ogori': localizations.cityOgori,
    'Chikushino': localizations.cityChikushino,
    'Kasuga': localizations.cityKasuga,
    'Onojo': localizations.cityOnojo,
    'Munakata': localizations.cityMunakata,
    'Dazaifu': localizations.cityDazaifu,
    'Fukutsu': localizations.cityFukutsu,
    'Ukiha': localizations.cityUkiha,
    'Miyawaka': localizations.cityMiyawaka,
    'Kama': localizations.cityKama,
    'Asakura': localizations.cityAsakura,
    'Miyama': localizations.cityMiyama,
    'Itoshima': localizations.cityItoshima,
    'Nakagawa': localizations.cityNakagawa,

    // --- Saga Prefecture ---
    'Saga': localizations.citySaga,
    'Saga City': localizations.citySagaCity,
    'Karatsu': localizations.cityKaratsu,
    'Tosu': localizations.cityTosu,
    'Taku': localizations.cityTaku,
    'Imari': localizations.cityImari,
    'Takeo': localizations.cityTakeo,
    'Kashima': localizations.cityKashima,
    'Ogi': localizations.cityOgi,
    'Ureshino': localizations.cityUreshino,
    'Kanzaki': localizations.cityKanzaki,

    // --- Nagasaki Prefecture ---
    'Nagasaki': localizations.cityNagasaki,
    'Nagasaki City': localizations.cityNagasakiCity,
    'Sasebo': localizations.citySasebo,
    'Shimabara': localizations.cityShimabara,
    'Isahaya': localizations.cityIsahaya,
    'Omura': localizations.cityOmura,
    'Hirado': localizations.cityHirado,
    'Matsuura': localizations.cityMatsuura,
    'Iki': localizations.cityIki,
    'Goto': localizations.cityGoto,
    'Saikai': localizations.citySaikai,
    'Unzen': localizations.cityUnzen,
    'Minamishimabara': localizations.cityMinamishimabara,

    // --- Kumamoto Prefecture ---
    'Kumamoto': localizations.cityKumamoto,
    'Kumamoto City': localizations.cityKumamotoCity,
    'Yatsushiro': localizations.cityYatsushiro,
    'Hitoyoshi': localizations.cityHitoyoshi,
    'Arao': localizations.cityArao,
    'Minamata': localizations.cityMinamata,
    'Tamana': localizations.cityTamana,
    'Yamaga': localizations.cityYamaga,
    'Kikuchi': localizations.cityKikuchi,
    'Uto': localizations.cityUto,
    'Kamiamakusa': localizations.cityKamiamakusa,
    'Uki': localizations.cityUki,
    'Aso': localizations.cityAso,
    'Amakusa': localizations.cityAmakusa,
    'Koshi': localizations.cityKoshi,

    // --- Oita Prefecture ---
    'Oita': localizations.cityOita,
    'Oita City': localizations.cityOitaCity,
    'Beppu': localizations.cityBeppu,
    'Nakatsu': localizations.cityNakatsu,
    'Hita': localizations.cityHita,
    'Saiki': localizations.citySaiki,
    'Usuki': localizations.cityUsuki,
    'Tsukumi': localizations.cityTsukumi,
    'Taketa': localizations.cityTaketa,
    'Bungotakada': localizations.cityBungotakada,
    'Kitsuki': localizations.cityKitsuki,
    'Usa': localizations.cityUsa,
    'Bungoono': localizations.cityBungoono,
    'Yufu': localizations.cityYufu,
    'Kunisaki': localizations.cityKunisaki,

    // --- Miyazaki Prefecture ---
    'Miyazaki': localizations.cityMiyazaki,
    'Miyazaki City': localizations.cityMiyazakiCity,
    'Miyakonojo': localizations.cityMiyakonojo,
    'Nobeoka': localizations.cityNobeoka,
    'Nichinan': localizations.cityNichinan,
    'Kobayashi': localizations.cityKobayashi,
    'Hyuga': localizations.cityHyuga,
    'Kushima': localizations.cityKushima,
    'Saito': localizations.citySaito,
    'Ebino': localizations.cityEbino,

    // --- Kagoshima Prefecture ---
    'Kagoshima': localizations.cityKagoshima,
    'Kagoshima City': localizations.cityKagoshimaCity,
    'Kanoya': localizations.cityKanoya,
    'Makurazaki': localizations.cityMakurazaki,
    'Akune': localizations.cityAkune,
    'Satsumasendai': localizations.citySatsumasendai,
    'Hioki': localizations.cityHioki,
    'Soo': localizations.citySoo,
    'Kirishima': localizations.cityKirishima,
    'Ichikikushikino': localizations.cityIchikikushikino,
    'Minamisatsuma': localizations.cityMinamisatsuma,
    'Ibusuki': localizations.cityIbusuki,
    'Nishinoomote': localizations.cityNishinoomote,
    'Tarumizu': localizations.cityTarumizu,
    'Aira': localizations.cityAira,
    'Isa': localizations.cityIsa,

    // --- Okinawa Prefecture ---
    'Okinawa': localizations.cityOkinawa,
    'Naha': localizations.cityNaha,
    'Ginowan': localizations.cityGinowan,
    'Ishigaki': localizations.cityIshigaki,
    'Urasoe': localizations.cityUrasoe,
    'Nago': localizations.cityNago,
    'Itoman': localizations.cityItoman,
    'Tomigusuku': localizations.cityTomigusuku,
    'Uruma': localizations.cityUruma,
    'Nanjo': localizations.cityNanjo,
  };

  // Return localized name or fall back to original name
  return localizationMap[locationName] ?? locationName;
}
